# -*- coding: utf-8 -*-
"""matplotlib-practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hltDARkYVUCMPMsZv5kbrypn6kh4EWvq
"""

pip install pandas matplotlib



#bar plot
import matplotlib.pyplot as plt

y=[98,99,88,78,65]
x=["Part1","Part2","Part3","Part4","Part5"]
colors=["blue","red","yellow","green","orange"]

plt.bar(x,y,color=colors,edgecolor="black")
plt.xlabel("Parts of Harry Potter", fontsize=12)
plt.ylabel("Popularity",fontsize=12)
plt.title("Popoularity of Different parts of Harry Potter",fontsize=18)
plt.savefig("bar.png")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_excel("/content/expense3.xlsx")
df = pd.DataFrame(data)
print(df)
grouped_by = df.groupby("Payment Mode")["Amount"].sum()
print(grouped_by)
plt.bar(grouped_by.index,grouped_by.values)
plt.show()

#line plot
import matplotlib.pyplot as plt

x=["day1","day2","day3","day4","day5"]
y=[300,420,250,230,400]
y1=[500,600,300,290,700]

plt.plot(x,y,marker="*",ls="--",color="red",label="week1")
plt.plot(x,y1,marker="*",ls="-",color="green",label="week2",alpha=0.5)
plt.legend()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_excel("/content/expense3.xlsx")
df=pd.DataFrame(data)
print(df)
groups=df.groupby("Category")["Amount"].sum()
print(groups)
print(groups.index.dtype)
groups.index = pd.Categorical(groups.index).codes
print(groups.index.dtype)

plt.plot(groups.index,groups.values)
plt.show()

#scatter plot
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

x = np.random.randint(1,10,50)
y= np.random.randint(10,100,50)
color=np.random.randint(10,100,50)

plt.scatter(x,y,marker="*",cmap="hot",c=color)
plt.colorbar()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

data = pd.read_excel("/content/ESD.xlsx")
df = pd.DataFrame(data)
print(df)

plt.scatter(df["Department"],df["Age"])
plt.show()

#pie chart
import matplotlib.pyplot as plt

brands = ["Oneplus","Apple","Samsung","Redmi"]
x=[22,35,30,10]
color=["purple","lightblue","yellow","orange"]
ex=[0,0,0,0.1]
plt.pie(x,labels=brands,colors=color,explode=ex,shadow=True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_excel("/content/expense3.xlsx")
df=pd.DataFrame(data)

grouped_by=df.groupby("Payment Mode")["Amount"].sum()
print(grouped_by)
plt.pie(grouped_by.values,labels=grouped_by.index,autopct="%.2f")
plt.show()
print(df)

#boxplot
import matplotlib.pyplot as plt
l = [25,46,57,25,45,13,29,39,46,99,22,12,14,55,6,46,52,55]
plt.boxplot(l)
plt.show()



import matplotlib.pyplot as plt
l = [1,3,4,7,12,2,8,9,24]
l2=[2,4,8,5,13,4,6,34,20]
plot_values = [l,l2]
plt.boxplot(plot_values)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_excel("/content/expense3.xlsx")
df=pd.DataFrame(data)

plt.boxplot(df["Amount"])
plt.show()
print(df)

#histogram
import matplotlib.pyplot as plt
x=[30,40,78,69,78,43,20,10,4,6,2,5,78]
plt.hist(x,bins=20,edgecolor="black",color="lightblue")
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

data = pd.read_excel("/content/ESD.xlsx")
df = pd.DataFrame(data)
print(df)

plt.hist(df["Age"],bins=10)
plt.show()

#violin plot
import matplotlib.pyplot as plt
a=[20,30,40,60,79,80,56,89,67,21,90,30]
plt.violinplot(a,showmedians=True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_excel("/content/ESD.xlsx")
df=pd.DataFrame(data)
print(df)
plt.violinplot(df["Annual Salary"],showmedians=True)
plt.show()

#stem plot
import matplotlib.pyplot as plt
x=[10,90,40,50,67,45,30,20,19,56]
plt.stem(x,linefmt="--",markerfmt="D",bottom = 1)
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

data = pd.read_excel("/content/ESD.xlsx")
df = pd.DataFrame(data)
df2 =(df.head(50))
plt.stem(df2["Annual Salary"])
plt.plot(df2["Annual Salary"])
plt.show()

#stack plot
import matplotlib.pyplot as plt
days = [1,2,3,4,5,6,7]
NOP1 = [5,10,20,30,56,60,80]
NOP2 = [10,30,50,60,20,40,55]
NOP3 = [30,10,40,50,80,70,60]

plt.stackplot(days,NOP1,NOP2,NOP3)
plt.show();

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("/content/food_data.csv")
df = pd.DataFrame(data)
print(df)
plt.stackplot(df["Calories"],df["Protein"],df["Fat"])
plt.legend()
plt.show()

#step plot
import matplotlib.pyplot as plt
x =["day1","day2","day3","day4"]
y=[30,40,60,20]
plt.step(x,y,where="post")
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
data = pd.read_excel("/content/expense3.xlsx")
df = pd.DataFrame(data)

df['Category'] = df['Category'].astype(str)
group = df.groupby("Category").agg({"Amount":"sum"})
print(group)
plt.step(group.index,group["Amount"],where="mid",marker="o")
plt.show()

#working with legends
import matplotlib.pyplot as plt
x=[1,2,3,4,5]
y=[45,67,89,76,34]
y1=[23,56,90,32,12]
plt.figure(figsize=[5,3])
plt.plot(x,y,label="male")
plt.plot(x,y1,label="female")
plt.legend(["m","f"],ncols=2)
plt.show()

#working of subplot
import matplotlib.pyplot as plt

x=[1,2,3,4,5]
y=[45,34,56,23,45]

plt.suptitle("Employee Data")
plt.subplot(2,2,1)
plt.title("age")
plt.bar(x,y)

x=[5,6,7,8,9]
y=[45,67,89,80,56]
plt.subplot(2,2,2)
plt.title("weight")
plt.plot(x,y)
plt.show()

x=[5,6,2,7,0]
y=[45,67,89,80,56]
plt.subplot(2,2,3)
plt.plot(x,y)

plt.show()

