# -*- coding: utf-8 -*-
"""seaborn-practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kPUB0jS8aWuSWFUNZ3JNXhbc8fG-o-tE
"""



pip install seaborn



#create line plot using seaborn
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

data ={"Days":[1,2,3,4,5],
       "NOP":[40,50,70,20,49]}
df = pd.DataFrame(data)
print(df)

sns.lineplot(data =data,x="Days",y="NOP")
plt.show()

data = pd.read_excel("/content/ESD.xlsx")
print(data)

sns.lineplot(data=data,x="Business Unit",y="Age",hue="Gender")

plt.show()

#barplot in seaborn
import seaborn as sns
import matplotlib.pyplot as plt
data = sns.load_dataset("tips")#load existing datasets from github using sns
print(data)

sns.barplot(data=data,x="day",y="tip",hue="sex")
plt.plot()

import seaborn as sns
import matplotlib.pyplot as plt
data = sns.load_dataset('tips')
print(data)
sns.histplot(data, x="day")
plt.show()

#scatterplot in seaborn
import seaborn as sns
import matplotlib.pyplot as plt
data = sns.load_dataset("tips")#load existing datasets from github using sns
print(data)

sns.scatterplot(data=data,x="total_bill",y="tip",hue="time")
plt.plot()

import pandas as pd
data = pd.read_excel("/content/ESD.xlsx")

#print(data)
sns.scatterplot(data =data,x="Age",y="Annual Salary",size="Bonus %")
plt.legend(bbox_to_anchor=(0.2,0,1.2,1))
plt.show()

#heatmap in seaborn
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

data = sns.load_dataset("tips")
print(data)

gp = data.groupby("day").agg({"tip":"mean"})
sns.heatmap(gp)
plt.show()

data = pd.read_excel("/content/ESD.xlsx")
gp= data.groupby("Job Title").agg({"Annual Salary":"mean"})
sns.heatmap(gp)
plt.show()

#countplot in seabron
data=sns.load_dataset("tips")
print(data)
sns.countplot(data = data,x="day")
plt.show()

data = pd.read_excel("/content/ESD.xlsx")
print(data)
sns.countplot(data=data,x="Department",hue="Gender")
plt.xlabel

#violin plot in seaborn
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
data = sns.load_dataset("tips")
print(data)
sns.violinplot(data=data,x="total_bill")

df= pd.read_excel("/content/ESD.xlsx")
#print(df)
sns.violinplot(data=df,x="Age")

data=sns.load_dataset("tips")
#print(data)
sns.pairplot(data,hue="day")

#strip plot in seaborn
data =sns.load_dataset("tips")
sns.stripplot(data=data,x='day',y='total_bill',hue="sex",dodge=True,jitter=0.3)
plt.show()

#box-plot in seaborn
data = sns.load_dataset("tips")
sns.boxplot(data=data,x="tip",y="sex",hue="day")
plt.show()

#catplot(catagorical plot) in seaborn

data= sns.load_dataset("tips")
sns.catplot(data=data,x="tip",y="day",kind="bar")
plt.show()

#style and color of plot in seaborn

data = sns.load_dataset("exercise")
sns.set_style(style="ticks")
sns.barplot(data=data,x="time",y="pulse")
plt.show()





sns.palplot(sns.color_palette())
plt.show()

data=sns.load_dataset("tips")
print(data)
a=sns.FacetGrid(data,col="day")
a.map(sns.barplot,"day","tip")
plt.show()

#relational plot in seaborn
data= sns.load_dataset("tips")
print(data)

sns.relplot(data=data,x="tip",y="total_bill",hue="sex",col="day")
plt.show()

#swarm plot in seaborn

data=sns.load_dataset("tips")
sns.swarmplot(data=data,x="day",y="total_bill",hue="sex",dodge=True)
plt.show()

#KDE plot in seaborn
data = sns.load_dataset("tips")
sns.kdeplot(data=data,x="total_bill",hue="day",multiple="stack")
plt.show()